# Generated by Django 3.2.7 on 2021-09-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210927_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='date_of_birth',
        ),
    ]
